version: 1.2
workflows:
       -  name: foobar
          subclass: wdl
          primaryDescriptorPath: /Dockstore2.wdl
          testParameterFiles:
              - /dockstore.wdl.json
       -  name: foobar2
          subclass: cwl
          primaryDescriptorPath: /Dockstore.cwl
          testParameterFiles:
              - /dockstore.cwl.json
