version: 1.2
workflows:
       -  name: <invalid>!/foobar
          subclass: wdl
          primaryDescriptorPath: /Dockstore2.wdl
          testParameterFiles:
              - /dockstore.wdl.json
          latestTagAsDefault: false
